### ISSUE TITLE
Repeated normalization/feature selection in pycytominer_operations?

### ISSUE THREAD

**Issue by bethac07** [ciminilab/2022_Garcia-Fossa_submitted#6]
In the util function [pycytominer_operations](https://github.com/ciminilab/2022_Garcia-Fossa_submitted/blob/main/utils/correlations.py#L18-L29), data is normalized and feature selected before aggregation. 

This function is used in the protocol 2 notebook at step 5, but per the [second prep notebook](https://github.com/ciminilab/2022_Garcia-Fossa_submitted/blob/main/basic_protocol_2/notebook/support%20notebooks/2_Generate_Profiles.ipynb), you've already performed normalization and feature selection. 

At what point is it intended that the researcher will do these steps- during prep or during the notebook? It definitely should not be done in both places.

**Comment by bethac07** [comment]
I would prefer, to the degree my input is helpful, doing it in step 5, because it means that in theory it is possible (see below) for a user to get through the entire notebook without actually interacting with any code at all. But I'm not unhappy with either choice.

- Have a small enough amount of data in the first place that this wouldn't entirely barf
- Bring your metadata into the CellProfiler Metadata module 
- Use ExportToSpreadsheet, turning on the option to put metadata on the object sheets
- Manually merge the object sheets in something like Excel or Google Sheets for both Cells and Cytoplasm, you'd want to re-order the rows to be by Image and Parent_Nuclei for the same issue discussed in #3, but that's pretty easy to do in either program

**Comment by fefossa** [comment]
1. I could add a step after importing the dataframe (section 3) to normalize and feature select and just do aggregate in step 5 (when I actually need the aggregated df to make the correlation matrix). 

2. For the metadata, I could add a function in section 3 as well and ask if the person already has the metadata in their dataset (because they already added it with cellprofiler or something), if not import the CSV and annotate the data. 

Would that be something that helps? 

3. If that seems too much to do right now I could just remove the normalization/feature selection in section 5 and only aggregate the dataframe in this step (that's what I should be doing since the beginning and not normalize/feat select twice for sure)
